Repository Team7-UPDO/Team7_UPDO, pull requests merged in 2025-09, with the labels that each got.

#16 [Setting] default 브랜치 변경
  .eslintignore
  .eslintrc.js
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc.js
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  commitlint.config.js
  eslint.config.mjs
  jest.config.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  vitest.config.ts
  vitest.shims.d.ts
Labels: ⚙️ Setting

#23 ⚙️ [Setting] default 브랜치 변경
  .storybook/Storybook.md
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/stories-samples/Avatar.tsx
  .storybook/stories-samples/TextField.tsx
  .storybook/stories-samples/stories/Avatar.stories.tsx
  .storybook/stories-samples/stories/TextField.stories.tsx
  src/components/ui/Button.tsx
  src/components/ui/Configure.mdx
  src/components/ui/Header.tsx
  src/components/ui/Page.tsx
  src/components/ui/assets/accessibility.png
  src/components/ui/assets/accessibility.svg
  src/components/ui/assets/addon-library.png
  src/components/ui/assets/assets.png
  src/components/ui/assets/avif-test-image.avif
  src/components/ui/assets/context.png
  src/components/ui/assets/discord.svg
  src/components/ui/assets/docs.png
  src/components/ui/assets/figma-plugin.png
  src/components/ui/assets/github.svg
  src/components/ui/assets/share.png
  src/components/ui/assets/styling.png
  src/components/ui/assets/testing.png
  src/components/ui/assets/theming.png
  src/components/ui/assets/tutorials.svg
  src/components/ui/assets/youtube.svg
  src/components/ui/button.css
  src/components/ui/header.css
  src/components/ui/page.css
  src/components/ui/stories/Button.stories.ts
  src/components/ui/stories/Header.stories.ts
  src/components/ui/stories/Page.stories.ts
Labels: ⚙️ Setting

#29 [CI] #28 pr checks 워크플로우 작성
  .github/workflows/pr-checks.yml
Labels: 🚀 Deploy

#34 Chore/#32 mirror repo
  .github/workflows/mirror-deploy.yml
  public/.gitkeep
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/page.tsx
Labels: 🚀 Deploy

#37 [FIX] #36 개인레포 워크플로우 비활성화
  .github/workflows/mirror-deploy.yml
Labels: 🚀 Deploy

#40 Feature/#38 chromatic ci workflow
  .github/workflows/chromatic.yml
Labels: 🚀 Deploy

#45 ⚙️ [Setting] 글로벌 스타일 시스템 초기 설정 #20
  .editorconfig
  .eslintrc.js
  .gitattributes
  .prettierrc.js
  .storybook/main.ts
  .storybook/samples/Button.stories.ts
  .storybook/samples/Button.tsx
  .storybook/samples/Configure.mdx
  .storybook/samples/Header.stories.ts
  .storybook/samples/Header.tsx
  .storybook/samples/Page.stories.ts
  .storybook/samples/Page.tsx
  .storybook/samples/assets/accessibility.png
  .storybook/samples/assets/accessibility.svg
  .storybook/samples/assets/addon-library.png
  .storybook/samples/assets/assets.png
  .storybook/samples/assets/avif-test-image.avif
  .storybook/samples/assets/context.png
  .storybook/samples/assets/discord.svg
  .storybook/samples/assets/docs.png
  .storybook/samples/assets/figma-plugin.png
  .storybook/samples/assets/github.svg
  .storybook/samples/assets/share.png
  .storybook/samples/assets/styling.png
  .storybook/samples/assets/testing.png
  .storybook/samples/assets/theming.png
  .storybook/samples/assets/tutorials.svg
  .storybook/samples/assets/youtube.svg
  .storybook/samples/button.css
  .storybook/samples/header.css
  .storybook/samples/page.css
  .storybook/stories/0-Tokens/Colors.stories.tsx
  .storybook/stories/0-Tokens/Playground.stories.tsx
  .storybook/stories/0-Tokens/Surfaces.stories.tsx
  .storybook/stories/0-Tokens/Typography.stories.tsx
  .storybook/stories/0-Tokens/UsageGuide.stories.tsx
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/components/ui/Avatar.stories.tsx
  src/components/ui/Avatar.tsx
  src/components/ui/TextField.stories.tsx
  src/components/ui/TextField.tsx
  src/lib/utils.ts
  src/styles/variants.ts
Labels: 🎨 Ui, 📄 Docs, ⚙️ Setting
